# Generated by Django 2.1.5 on 2019-10-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='endPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='startPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
