# Generated by Django 2.1.5 on 2019-11-19 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_table2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table2',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='check_in',
            field=models.DateField(default=datetime.datetime(2019, 11, 19, 5, 52, 26, 308712)),
        ),
        migrations.AlterField(
            model_name='session',
            name='check_out',
            field=models.DateField(default=datetime.datetime(2019, 11, 19, 5, 52, 26, 308741)),
        ),
    ]
