# Generated by Django 2.2.6 on 2019-11-19 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20191119_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='check_in',
            field=models.DateField(default=datetime.datetime(2019, 11, 19, 17, 52, 35, 404780)),
        ),
        migrations.AlterField(
            model_name='session',
            name='check_out',
            field=models.DateField(default=datetime.datetime(2019, 11, 19, 17, 52, 35, 404780)),
        ),
    ]
