# Generated by Django 2.2.6 on 2019-11-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20191119_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.AddField(
            model_name='hotel',
            name='review',
            field=models.CharField(default='empty', max_length=1000000000),
        ),
    ]
