# Generated by Django 2.2.6 on 2019-11-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20191119_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='max_rooms_available',
            field=models.IntegerField(default=20),
        ),
    ]
